# Propriedades da aplicação Spring Boot
profiles: universe

# Configurações da aplicação
universe:
  backing-services:
    database:
      username: UniverseAdmin
      password: admin
      url: jdbc:postgresql://localhost:5432/UniverseDataBase
      driver-class-name: org.postgresql.Driver   

# Porta do servidor
server:
  port: 8080
# Configurações de banco de dados
spring.jpa:
  show-sql: true
  generate-ddl: false
  hibernate:
    ddl-auto: none

logging:
  group:
    web: org.springframework.core.codec, org.springframework.http, org.springframework.web
    spring: org.springframework.core.env
    servlet: org.springframework.boot.web, org.apache.catalina, org.apache.coyote, org.apache.tomcat
    data: org.springframework.jdbc.core, org.hibernate.sql, org.springframework.orm.jpa, com.zaxxer.hikari, org.hibernate, org.jooq.tools.LoggerListener
    app: com.project.universe
  level:
    root: WARN
    spring: INFO
    app: DEBUG
    servlet: WARN
    web: WARN
    data: INFO
